apiVersion: 1
datasources:
  - name: PostgreSQL
    type: grafana-postgresql-datasource
    uid: weather-postgres
    url: postgres:5432
    user: postgres
    jsonData:
      database: weather
      sslmode: disable
    secureJsonData:
      password: $DB_PASSWORD