apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data
spec:
  accessModes: ["ReadWriteOnce"] # 노드 하나에서 읽기 쓰기 - DB는 이거면 됨
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: postgres
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: postgres
    spec:
      # 이 Pod는 이 디스크를 쓴다. 선언
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: postgres-data
      containers:
      - image: postgres:16-alpine
        name: postgres
        env:
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                key: POSTGRES_PASSWORD
                name: postgres-credentials
          - name: POSTGRES_DB
            value: weather
        # 그 디스크를 컨테이너의 이 경로에 꽂는다.
        volumeMounts:
          - mountPath: /var/lib/postgresql/data
            name: data
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: postgres
  name: postgres
spec:
  ports:
  - port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: postgres
